#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

#include "XamlBindingInfo.g.h"


namespace BackgroundHost
{
    namespace Headed
    {
        namespace Views
        {
            [::Windows::Foundation::Metadata::WebHostHidden]
            partial ref class ServiceOperationView : public ::Windows::UI::Xaml::Controls::UserControl, 
                public ::Windows::UI::Xaml::Markup::IComponentConnector,
                public ::Windows::UI::Xaml::Markup::IComponentConnector2
            {
            public:
                void InitializeComponent();
                virtual void Connect(int connectionId, ::Platform::Object^ target);
                virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
            
            private:
                bool _contentLoaded;
                class ServiceOperationView_obj1_Bindings;
            
                ::XamlBindingInfo::XamlBindings^ Bindings;
            };
        }
    }
}

